"""assessment study buddy final exam

Revision ID: 044bc2d07701
Revises: 6aea930ec890
Create Date: 2026-07-27 20:01:07.703486
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '044bc2d07701'
down_revision: str | None = '6aea930ec890'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('final_exam_submissions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('file_url', sa.String(length=512), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'course_id', name='uq_final_exam_submission')
    )
    op.create_index(op.f('ix_final_exam_submissions_course_id'), 'final_exam_submissions', ['course_id'], unique=False)
    op.create_index(op.f('ix_final_exam_submissions_user_id'), 'final_exam_submissions', ['user_id'], unique=False)
    op.create_table('skills_assessments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('ai_score_pct', sa.Integer(), nullable=False),
    sa.Column('ai_readiness_pct', sa.Integer(), nullable=False),
    sa.Column('ai_feedback', sa.Text(), nullable=False),
    sa.Column('ai_verdict', sa.String(length=16), nullable=False),
    sa.Column('mentor_verdict', sa.String(length=16), nullable=True),
    sa.Column('mentor_feedback', sa.Text(), nullable=True),
    sa.Column('mentor_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mentor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'course_id', name='uq_skills_assessment')
    )
    op.create_index(op.f('ix_skills_assessments_course_id'), 'skills_assessments', ['course_id'], unique=False)
    op.create_index(op.f('ix_skills_assessments_user_id'), 'skills_assessments', ['user_id'], unique=False)
    op.create_table('quizzes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('module_id', sa.BigInteger(), nullable=True),
    sa.Column('course_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('pass_score_pct', sa.Integer(), nullable=False),
    sa.Column('time_limit_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(module_id IS NOT NULL AND course_id IS NULL) OR (module_id IS NULL AND course_id IS NOT NULL)', name='ck_quiz_exactly_one_scope'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['module_id'], ['course_modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', name='uq_quiz_course'),
    sa.UniqueConstraint('module_id', name='uq_quiz_module')
    )
    op.create_table('quiz_attempts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('quiz_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('question_ids', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('answers', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('score_pct', sa.Integer(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('expired', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_attempts_quiz_id'), 'quiz_attempts', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_user_id'), 'quiz_attempts', ['user_id'], unique=False)
    op.create_table('quiz_questions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('quiz_id', sa.BigInteger(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('choices', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('correct_index', sa.Integer(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_questions_quiz_id'), 'quiz_questions', ['quiz_id'], unique=False)
    op.create_table('study_buddy_messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('lesson_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_buddy_messages_lesson_id'), 'study_buddy_messages', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_study_buddy_messages_user_id'), 'study_buddy_messages', ['user_id'], unique=False)
    op.add_column('certificates', sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('certificates', sa.Column('readiness_pct', sa.Integer(), nullable=True))
    op.add_column('courses', sa.Column('final_exam_brief', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'final_exam_brief')
    op.drop_column('certificates', 'readiness_pct')
    op.drop_column('certificates', 'confirmed_at')
    op.drop_index(op.f('ix_study_buddy_messages_user_id'), table_name='study_buddy_messages')
    op.drop_index(op.f('ix_study_buddy_messages_lesson_id'), table_name='study_buddy_messages')
    op.drop_table('study_buddy_messages')
    op.drop_index(op.f('ix_quiz_questions_quiz_id'), table_name='quiz_questions')
    op.drop_table('quiz_questions')
    op.drop_index(op.f('ix_quiz_attempts_user_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_quiz_id'), table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    op.drop_table('quizzes')
    op.drop_index(op.f('ix_skills_assessments_user_id'), table_name='skills_assessments')
    op.drop_index(op.f('ix_skills_assessments_course_id'), table_name='skills_assessments')
    op.drop_table('skills_assessments')
    op.drop_index(op.f('ix_final_exam_submissions_user_id'), table_name='final_exam_submissions')
    op.drop_index(op.f('ix_final_exam_submissions_course_id'), table_name='final_exam_submissions')
    op.drop_table('final_exam_submissions')
    # ### end Alembic commands ###
