"""passport: username, visibility, certificate pdf, portfolio

Revision ID: 4937c7b61be5
Revises: d9887731ac74
Create Date: 2026-07-10 22:26:24.635524
"""

import re
import secrets
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4937c7b61be5"
down_revision: str | None = "d9887731ac74"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _slugify(full_name: str) -> str:
    base = full_name.lower()
    base = re.sub(r"[^a-z0-9]+", "_", base).strip("_")
    return base[:24] or "user"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "portfolio_items",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("media_urls", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("source_type", sa.String(length=16), nullable=False),
        sa.Column("submission_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["submission_id"], ["submissions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_portfolio_items_user_id"), "portfolio_items", ["user_id"], unique=False
    )
    op.add_column("certificates", sa.Column("pdf_url", sa.String(length=512), nullable=True))
    op.create_unique_constraint(
        "uq_certificate_user_course", "certificates", ["user_id", "course_id"]
    )
    op.create_foreign_key(
        None, "certificates", "courses", ["course_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###

    # --- users.passport_visibility: server_default mavjud qatorlarni ham qamrab oladi ---
    op.add_column(
        "users",
        sa.Column(
            "passport_visibility", sa.String(length=16), server_default="unlisted", nullable=False
        ),
    )

    # --- users.username: avval nullable qo'shamiz, mavjud qatorlarni backfill qilamiz,
    #     so'ng NOT NULL + unique index o'rnatamiz ---
    op.add_column("users", sa.Column("username", sa.String(length=40), nullable=True))

    connection = op.get_bind()
    existing = connection.execute(sa.text("SELECT id, full_name FROM users")).fetchall()
    used: set[str] = set()
    for row in existing:
        base = _slugify(row.full_name)
        candidate = f"{base}_{secrets.token_hex(3)}"
        while candidate in used:
            candidate = f"{base}_{secrets.token_hex(3)}"
        used.add(candidate)
        connection.execute(
            sa.text("UPDATE users SET username = :u WHERE id = :id"),
            {"u": candidate, "id": row.id},
        )

    op.alter_column("users", "username", nullable=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_column("users", "passport_visibility")
    op.drop_column("users", "username")
    op.drop_constraint(None, "certificates", type_="foreignkey")
    op.drop_constraint("uq_certificate_user_course", "certificates", type_="unique")
    op.drop_column("certificates", "pdf_url")
    op.drop_index(op.f("ix_portfolio_items_user_id"), table_name="portfolio_items")
    op.drop_table("portfolio_items")
    # ### end Alembic commands ###
