"""certificates

Revision ID: 4b1e15394cab
Revises: 03e7a29cd7f8
Create Date: 2026-07-09 18:39:43.609439
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4b1e15394cab"
down_revision: str | None = "03e7a29cd7f8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "certificates",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("course_id", sa.BigInteger(), nullable=True),
        sa.Column("uid", sa.String(length=64), nullable=False),
        sa.Column("qr_url", sa.String(length=512), nullable=True),
        sa.Column(
            "issued_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_certificates_uid"), "certificates", ["uid"], unique=True)
    op.create_index(op.f("ix_certificates_user_id"), "certificates", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_certificates_user_id"), table_name="certificates")
    op.drop_index(op.f("ix_certificates_uid"), table_name="certificates")
    op.drop_table("certificates")
    # ### end Alembic commands ###
