"""donation projects

Revision ID: 6aea930ec890
Revises: 26fc19839096
Create Date: 2026-07-27 17:59:08.077521
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6aea930ec890"
down_revision: str | None = "26fc19839096"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "donation_projects",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("story", sa.Text(), nullable=False),
        sa.Column("target_amount", sa.Integer(), nullable=False),
        sa.Column("collected_amount", sa.Integer(), nullable=False),
        sa.Column("deadline", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("report", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_donation_projects_owner_id"), "donation_projects", ["owner_id"], unique=False
    )
    op.create_table(
        "donations",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("project_id", sa.BigInteger(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("donor_name", sa.String(length=160), nullable=True),
        sa.Column("donor_email", sa.String(length=255), nullable=True),
        sa.Column("is_anonymous", sa.Boolean(), nullable=False),
        sa.Column("provider", sa.String(length=16), nullable=True),
        sa.Column("provider_transaction_id", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["donation_projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_donations_project_id"), "donations", ["project_id"], unique=False)
    op.create_index(
        op.f("ix_donations_provider_transaction_id"),
        "donations",
        ["provider_transaction_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_donations_provider_transaction_id"), table_name="donations")
    op.drop_index(op.f("ix_donations_project_id"), table_name="donations")
    op.drop_table("donations")
    op.drop_index(op.f("ix_donation_projects_owner_id"), table_name="donation_projects")
    op.drop_table("donation_projects")
    # ### end Alembic commands ###
