"""lesson hls key

Revision ID: 9889e1d15709
Revises: cc5872f07054
Create Date: 2026-07-27 22:26:46.411377
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9889e1d15709'
down_revision: str | None = 'cc5872f07054'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('hls_key_hex', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'hls_key_hex')
    # ### end Alembic commands ###
