"""course reviews views generosity

Revision ID: cc5872f07054
Revises: 044bc2d07701
Create Date: 2026-07-27 21:29:38.732381
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cc5872f07054'
down_revision: str | None = '044bc2d07701'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_reviews',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('instructor_reply', sa.Text(), nullable=True),
    sa.Column(
        'created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False
    ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'user_id', name='uq_course_review')
    )
    op.create_index(
        op.f('ix_course_reviews_course_id'), 'course_reviews', ['course_id'], unique=False
    )
    op.create_index(
        op.f('ix_course_reviews_user_id'), 'course_reviews', ['user_id'], unique=False
    )
    op.add_column(
        'courses', sa.Column('views_count', sa.Integer(), nullable=False, server_default='0')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_role', 'user_roles', type_='unique')
    op.drop_column('courses', 'views_count')
    op.drop_index(op.f('ix_course_reviews_user_id'), table_name='course_reviews')
    op.drop_index(op.f('ix_course_reviews_course_id'), table_name='course_reviews')
    op.drop_table('course_reviews')
    # ### end Alembic commands ###
