"""academy: courses, modules, lessons, enrollments

Revision ID: d9887731ac74
Revises: 4b1e15394cab
Create Date: 2026-07-09 18:53:56.926176
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d9887731ac74"
down_revision: str | None = "4b1e15394cab"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "course_categories",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("key", sa.String(length=4), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("ladder_step", sa.Integer(), nullable=False),
        sa.Column("sort", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "courses",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("instructor_id", sa.BigInteger(), nullable=False),
        sa.Column("category_id", sa.BigInteger(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=220), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("ladder_step", sa.Integer(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("is_free", sa.Boolean(), nullable=False),
        sa.Column("cover_url", sa.String(length=512), nullable=True),
        sa.Column("trailer_url", sa.String(length=512), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("rating", sa.Float(), nullable=False),
        sa.Column("students_count", sa.Integer(), nullable=False),
        sa.Column("income_success_rate", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["course_categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instructor_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_courses_instructor_id"), "courses", ["instructor_id"], unique=False)
    op.create_index(op.f("ix_courses_slug"), "courses", ["slug"], unique=True)
    op.create_table(
        "course_modules",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("course_id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("sort", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["course_id"], ["courses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_course_modules_course_id"), "course_modules", ["course_id"], unique=False
    )
    op.create_table(
        "enrollments",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("course_id", sa.BigInteger(), nullable=False),
        sa.Column("progress_pct", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["course_id"], ["courses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "course_id", name="uq_enrollment"),
    )
    op.create_index(op.f("ix_enrollments_course_id"), "enrollments", ["course_id"], unique=False)
    op.create_index(op.f("ix_enrollments_user_id"), "enrollments", ["user_id"], unique=False)
    op.create_table(
        "assignments",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("module_id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("sort", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["module_id"], ["course_modules.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_assignments_module_id"), "assignments", ["module_id"], unique=False)
    op.create_table(
        "lessons",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("module_id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("raw_video_key", sa.String(length=512), nullable=True),
        sa.Column("hls_url", sa.String(length=512), nullable=True),
        sa.Column("subtitle_url", sa.String(length=512), nullable=True),
        sa.Column("transcript", sa.Text(), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("sort", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["module_id"], ["course_modules.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_lessons_module_id"), "lessons", ["module_id"], unique=False)
    op.create_table(
        "lesson_completions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("enrollment_id", sa.BigInteger(), nullable=False),
        sa.Column("lesson_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["enrollment_id"], ["enrollments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["lesson_id"], ["lessons.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("enrollment_id", "lesson_id", name="uq_lesson_completion"),
    )
    op.create_index(
        op.f("ix_lesson_completions_enrollment_id"),
        "lesson_completions",
        ["enrollment_id"],
        unique=False,
    )
    op.create_table(
        "submissions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("assignment_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("file_url", sa.String(length=512), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("feedback", sa.Text(), nullable=True),
        sa.Column("reviewed_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["assignment_id"], ["assignments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_submissions_assignment_id"), "submissions", ["assignment_id"], unique=False
    )
    op.create_index(op.f("ix_submissions_user_id"), "submissions", ["user_id"], unique=False)
    # ### end Alembic commands ###

    # --- Seed: kurs kategoriyalari (Vision Book 3.3) ---
    cat = sa.table(
        "course_categories",
        sa.column("key", sa.String),
        sa.column("name", sa.String),
        sa.column("ladder_step", sa.Integer),
        sa.column("sort", sa.Integer),
    )
    op.bulk_insert(
        cat,
        [
            {"key": "A", "name": "Hunarmandchilik va qo'l mehnati", "ladder_step": 1, "sort": 1},
            {"key": "B", "name": "Oziq-ovqat va xizmat", "ladder_step": 1, "sort": 2},
            {"key": "C", "name": "Qishloq xo'jaligi va uy xo'jaligi", "ladder_step": 1, "sort": 3},
            {"key": "D", "name": "Texnik va ta'mirlash ishlari", "ladder_step": 1, "sort": 4},
            {"key": "E", "name": "Ofis va masofaviy ishlar", "ladder_step": 1, "sort": 5},
            {"key": "F", "name": "Ijodiy va raqamli kasblar", "ladder_step": 2, "sort": 6},
            {"key": "G", "name": "IT (yuqori daraja)", "ladder_step": 3, "sort": 7},
            {"key": "H", "name": "Tadbirkorlik va soft skills", "ladder_step": 4, "sort": 8},
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_submissions_user_id"), table_name="submissions")
    op.drop_index(op.f("ix_submissions_assignment_id"), table_name="submissions")
    op.drop_table("submissions")
    op.drop_index(op.f("ix_lesson_completions_enrollment_id"), table_name="lesson_completions")
    op.drop_table("lesson_completions")
    op.drop_index(op.f("ix_lessons_module_id"), table_name="lessons")
    op.drop_table("lessons")
    op.drop_index(op.f("ix_assignments_module_id"), table_name="assignments")
    op.drop_table("assignments")
    op.drop_index(op.f("ix_enrollments_user_id"), table_name="enrollments")
    op.drop_index(op.f("ix_enrollments_course_id"), table_name="enrollments")
    op.drop_table("enrollments")
    op.drop_index(op.f("ix_course_modules_course_id"), table_name="course_modules")
    op.drop_table("course_modules")
    op.drop_index(op.f("ix_courses_slug"), table_name="courses")
    op.drop_index(op.f("ix_courses_instructor_id"), table_name="courses")
    op.drop_table("courses")
    op.drop_table("course_categories")
    # ### end Alembic commands ###
