"""SQLAlchemy modellari — Alembic autogenerate va ilova uchun yagona kirish."""

from app.models.ai import (
    AiUsage,
    CareerCoachMessage,
    CaseStoryMessage,
    CaseStorySession,
    GeneratedCv,
    InterviewMessage,
    InterviewSession,
    PlacementTestMessage,
    PlacementTestSession,
    StudyBuddyMessage,
)
from app.models.assessment import (
    FinalExamSubmission,
    Quiz,
    QuizAttempt,
    QuizQuestion,
    SkillsAssessment,
)
from app.models.audit import AuditLog
from app.models.benefits import Benefit, UserBenefit
from app.models.certificate import Certificate
from app.models.course import (
    Assignment,
    Course,
    CourseCategory,
    CourseModule,
    Enrollment,
    Lesson,
    LessonCompletion,
    Submission,
)
from app.models.course_review import CourseReview
from app.models.donation import Donation, DonationProject
from app.models.live_lesson import LiveLesson
from app.models.donor import DonorProgram, ProgramEnrollment
from app.models.employer import Application, Company, CompanyMember, Placement, Vacancy
from app.models.enums import (
    AiFeature,
    ApplicationStatus,
    AssessmentVerdict,
    BenefitAudience,
    BenefitCategory,
    BenefitStatus,
    CompanyMemberRole,
    CourseStatus,
    DisabilityGroup,
    DisputeStatus,
    DonationProjectStatus,
    DonorProgramStatus,
    EmploymentType,
    EnrollmentStatus,
    Gender,
    GigStatus,
    InterviewSessionStatus,
    LessonStatus,
    MentorshipStatus,
    MessageRole,
    NotificationCategory,
    NotificationType,
    OrderStatus,
    PassportVisibility,
    PaymentProvider,
    PaymentStatus,
    PortfolioSource,
    ProgramEnrollmentStatus,
    QuizKind,
    RoleCode,
    SubmissionStatus,
    SubscriptionGrantedBy,
    SubscriptionPlan,
    SuccessStoryStatus,
    SupportResourceCategory,
    UserStatus,
    VacancyStatus,
    VerifiedStatus,
    WorkFormat,
)
from app.models.external_job import ExternalJob
from app.models.lesson_material import LessonMaterial
from app.models.marketplace import (
    Dispute,
    Gig,
    Order,
    OrderMessage,
    OrderMilestone,
    Payment,
    Review,
)
from app.models.mentorship import MentorCheckin, Mentorship
from app.models.notification import Notification
from app.models.peer_support import PeerSupportPost, PeerSupportReport, PeerSupportRoom
from app.models.portfolio import PortfolioItem, PortfolioItemStep
from app.models.streak import UserStreak
from app.models.subscription import Subscription
from app.models.subscription_purchase import SubscriptionPurchase
from app.models.success_story import SuccessStory
from app.models.support import SupportContent, SupportResource
from app.models.telegram import TelegramLink, TelegramLinkCode
from app.models.user import (
    DisabilityProfile,
    PhoneVerification,
    RefreshToken,
    Region,
    Role,
    User,
    UserRole,
)

__all__ = [
    "AiFeature",
    "AiUsage",
    "Application",
    "ApplicationStatus",
    "AssessmentVerdict",
    "Assignment",
    "AuditLog",
    "Benefit",
    "BenefitAudience",
    "BenefitCategory",
    "BenefitStatus",
    "CareerCoachMessage",
    "CaseStoryMessage",
    "CaseStorySession",
    "Certificate",
    "Company",
    "CompanyMember",
    "CompanyMemberRole",
    "Course",
    "CourseCategory",
    "CourseModule",
    "CourseReview",
    "CourseStatus",
    "DisabilityGroup",
    "DisabilityProfile",
    "Dispute",
    "DisputeStatus",
    "Donation",
    "DonationProject",
    "DonationProjectStatus",
    "DonorProgram",
    "DonorProgramStatus",
    "EmploymentType",
    "Enrollment",
    "EnrollmentStatus",
    "ExternalJob",
    "FinalExamSubmission",
    "Gender",
    "GeneratedCv",
    "Gig",
    "GigStatus",
    "InterviewMessage",
    "InterviewSession",
    "InterviewSessionStatus",
    "Lesson",
    "LessonCompletion",
    "LessonMaterial",
    "LessonStatus",
    "LiveLesson",
    "MentorCheckin",
    "Mentorship",
    "MentorshipStatus",
    "MessageRole",
    "Notification",
    "NotificationCategory",
    "NotificationType",
    "Order",
    "OrderMessage",
    "OrderMilestone",
    "OrderStatus",
    "PassportVisibility",
    "Payment",
    "PaymentProvider",
    "PaymentStatus",
    "PeerSupportPost",
    "PeerSupportReport",
    "PeerSupportRoom",
    "PhoneVerification",
    "Placement",
    "PlacementTestMessage",
    "PlacementTestSession",
    "PortfolioItem",
    "PortfolioItemStep",
    "PortfolioSource",
    "ProgramEnrollment",
    "ProgramEnrollmentStatus",
    "Quiz",
    "QuizAttempt",
    "QuizKind",
    "QuizQuestion",
    "RefreshToken",
    "Region",
    "Review",
    "Role",
    "RoleCode",
    "SkillsAssessment",
    "StudyBuddyMessage",
    "Submission",
    "SubmissionStatus",
    "Subscription",
    "SubscriptionGrantedBy",
    "SubscriptionPlan",
    "SubscriptionPurchase",
    "SuccessStory",
    "SuccessStoryStatus",
    "SupportContent",
    "SupportResource",
    "SupportResourceCategory",
    "TelegramLink",
    "TelegramLinkCode",
    "User",
    "UserBenefit",
    "UserRole",
    "UserStatus",
    "UserStreak",
    "Vacancy",
    "VacancyStatus",
    "VerifiedStatus",
    "WorkFormat",
]
